# site settings
title: Lab | Jeremias Menichelli
author: Jeremias Menichelli
description: "Lab description."
url: "http://jeremenichelli.github.io/lab"
baseurl: ""

# build settings
port: 5000
highlighter: pygments
markdown: redcarpet
