# site settings
title: LAB_NAME | Jeremias Menichelli
author: Jeremias Menichelli
description: "Lab description."
url: "http://jeremenichelli.github.io/LAB_NAME"
# change baseurl for LAB_NAME
baseurl: /labstheme

# build settings
port: 5000
highlighter: pygments
markdown: redcarpet
